# -*- coding: utf-8 -*-
"""Dodatkowe_300136.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pGXhMfdF_hdOb7oGkt7GbgCpISyROOKh
"""

#Instalacja sieci Kohonena
!pip3 install sklearn_som

import numpy as np
import pandas as pd
from scipy import stats
from sklearn_som.som import SOM

from google.colab import files #Wrzucenie pliku csv do colaba
uploaded = files.upload()      # otwierajac normalnie plik .py nie trzeba wywolywac

data = pd.read_csv("./churn_pl_wybrane.csv",sep=",",decimal=".") # wczytanie pliku csv

data_stand=data[['Czaswspolpracy', 'Liczbawiadomosci', 'Dzienminuty', 'Dzienrozmowy', 'Wieczorminuty','Wieczorrozmowy','Nocminuty','Nocrozmowy','Miedzynarodoweminuty','Miedzynarodowerozmowy','LiczbarozmowzBOK','Planmiedzy01','Pocztagl01']]
data_stand=stats.zscore(data_stand) #standaryzacja danych

data_som=np.array(data_stand)
kohonen = SOM(m=3, n=3, dim=13)
kohonen.fit(data_som)
data['Klastry'] = kohonen.predict(data_som)

#Klaster 0
# Pakiet: duza liczba smsów + wieczornych i nocnych rozmów dla nowych klientow z pocztą glosową
print("Liczebnosc klastra:\t\t"+str(len(data[data['Klastry'] == 0])))
(data[data['Klastry'] == 0]).mean()

#Klaster 1
# Pakiet: Pakiet sms + wieczorne i nocne rozmowy dla lojalnych klientów zainteresowanych pocztą głosową
print("Liczebnosc klastra:\t\t"+str(len(data[data['Klastry'] == 1])))
(data[data['Klastry'] == 1]).mean()

#Klaster 2
# Pakiet: Dużo rozmów przez całą dobę bez miedzynarodowych połączeń dla klientów lojalnych
print("Liczebnosc klastra:\t\t"+str(len(data[data['Klastry'] == 2])))
(data[data['Klastry'] == 2]).mean()

#Klaster 3
# Pakiet: pakiet sms + wieczorne i nocne rozmowy dla nowych klientow korzystających z poczty glosowej i zainteresowanych polaczeniami miedzynarodowymi
print("Liczebnosc klastra:\t\t"+str(len(data[data['Klastry'] == 3])))
(data[data['Klastry'] == 3]).mean()

#Klaster 4
# Pakiet: Wieczorny i nocny pakiet rozmów dla nowych klientów razem z polaczeniami miedzynarodowymi
print("Liczebnosc klastra:\t\t"+str(len(data[data['Klastry'] == 4])))
(data[data['Klastry'] == 4]).mean()

#Klaster 5
# Pakiet: pakiet rozmow wieczornych i nocnych dla nowych klientów bez połączeń międzynarodowych
print("Liczebnosc klastra:\t\t"+str(len(data[data['Klastry'] == 5])))
(data[data['Klastry'] == 5]).mean()

#Klaster 6
# Pakiet: mała liczba smsów  + pakiet rozmów przez całą dobę dla klientów lojalnościowych z pakietem miedzynarodowym
print("Liczebnosc klastra:\t\t"+str(len(data[data['Klastry'] == 6])))
(data[data['Klastry'] == 6]).mean()

#Klaster 7
# Pakiet: pakiet oszczednosciowy dla nowych klientów. (lubiacych rozmawiac z BOK)
print("Liczebnosc klastra:\t\t"+str(len(data[data['Klastry'] == 7])))
(data[data['Klastry'] == 7]).mean()

#Klaster 8
# Pakiet: Rozmowy wieczorne i nocne + miedzynarodowe dla lojalnych klientów
print("Liczebnosc klastra:\t\t"+str(len(data[data['Klastry'] == 8])))
(data[data['Klastry'] == 8]).mean()